services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/srv/task-management.com
    ports:
      - "8080:80"
      - "5173:5173"
    command: bash -c "chmod 755 /srv/task-management.com/docker/web/start.sh &&
             /srv/task-management.com/docker/web/start.sh"
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      interval: 5s
      retries: 10